# calibration body settings
# chessboard
board_size_x_default: 10
board_size_y_default: 10
board_size_x_min: 5
board_size_y_min: 5
board_size_x_max: 20
board_size_y_max: 20

square_size_default: 50
square_size_min: 10
square_size_max: 100

# charuco
marker_no_x_default: 10
marker_no_y_default: 10
marker_no_x_min: 5
marker_no_y_min: 5
marker_no_x_max: 20
marker_no_y_max: 20

marker_size_default: 50
marker_size_min: 10
marker_size_max: 100